Repository prgrms-web-devcourse/Team_MODI_MODI_BE, pull requests merged in 2021-12, with the labels that each got.

#4 [MODI-18] Jacoco와 Swagger 관련 설정 추가
  build.gradle
  src/main/java/com/prgrms/modi/common/configuration/SwaggerConfiguration.java
  src/main/java/com/prgrms/modi/common/configuration/WebSecurityConfiguration.java
Labels: ✨ feature, 💻 infra

#3 [MODI-63] 전체 엔티티 객체 구현
  src/main/java/com/prgrms/modi/history/domain/CommissionDetail.java
  src/main/java/com/prgrms/modi/history/domain/CommissionHistory.java
  src/main/java/com/prgrms/modi/history/domain/PointDetail.java
  src/main/java/com/prgrms/modi/history/domain/PointHistory.java
  src/main/java/com/prgrms/modi/ott/domain/OTT.java
  src/main/java/com/prgrms/modi/party/domain/Party.java
  src/main/java/com/prgrms/modi/party/domain/PartyRule.java
  src/main/java/com/prgrms/modi/party/domain/PartyRulePK.java
  src/main/java/com/prgrms/modi/party/domain/PartyStatus.java
  src/main/java/com/prgrms/modi/party/domain/Rule.java
  src/main/java/com/prgrms/modi/user/domain/Member.java
  src/main/java/com/prgrms/modi/user/domain/User.java
Labels: 👥 review, ✨ feature

#5 [MODI-65] 시드 데이터 sql 작성
  src/main/java/com/prgrms/modi/history/domain/CommissionHistory.java
  src/main/java/com/prgrms/modi/party/domain/PartyRule.java
  src/main/resources/application.yaml
  src/main/resources/data.sql
Labels: ✨ feature

#9 [MODI-70] 닉네임 랜덤 생성기 구현
  src/main/java/com/prgrms/modi/user/service/UserService.java
  src/main/java/com/prgrms/modi/utils/UsernameGenerator.java
Labels: ✨ feature

#11 [MODI-76] 파티 목록 조회 API
  build.gradle
  src/main/java/com/prgrms/modi/error/GlobalExceptionHandler.java
  src/main/java/com/prgrms/modi/ott/domain/OTT.java
  src/main/java/com/prgrms/modi/ott/service/OttService.java
  src/main/java/com/prgrms/modi/party/PartyController.java
  src/main/java/com/prgrms/modi/party/PartyRepository.java
  src/main/java/com/prgrms/modi/party/PartyService.java
  src/main/java/com/prgrms/modi/party/domain/Party.java
  src/main/java/com/prgrms/modi/party/dto/PartyListResponse.java
  src/main/java/com/prgrms/modi/party/dto/PartyResponse.java
  src/main/resources/data.sql
  src/test/java/com/prgrms/modi/party/PartyControllerTest.java
  src/test/java/com/prgrms/modi/party/PartyServiceTest.java
  src/test/resources/application.yaml
Labels: 👥 review, ✨ feature

#12 [MODI-74] FEAT : Ott 단건 조회 구현
  src/main/java/com/prgrms/modi/ott/controller/OttRestController.java
  src/main/java/com/prgrms/modi/ott/domain/OTT.java
  src/main/java/com/prgrms/modi/ott/dto/OttResponse.java
  src/main/java/com/prgrms/modi/ott/service/OttService.java
  src/test/java/com/prgrms/modi/ott/controller/OttRestControllerTest.java
  src/test/java/com/prgrms/modi/ott/service/OttServiceTest.java
Labels: ✨ feature

#13 [MODI-84] 유저 정보 조회 기능 구현
  src/main/java/com/prgrms/modi/common/configuration/SwaggerConfiguration.java
  src/main/java/com/prgrms/modi/common/configuration/WebSecurityConfiguration.java
  src/main/java/com/prgrms/modi/common/jwt/Jwt.java
  src/main/java/com/prgrms/modi/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/modi/common/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/prgrms/modi/error/GlobalExceptionHandler.java
  src/main/java/com/prgrms/modi/error/exception/ForbiddenException.java
  src/main/java/com/prgrms/modi/user/controller/UserController.java
  src/main/java/com/prgrms/modi/user/domain/User.java
  src/main/java/com/prgrms/modi/user/dto/UserResponse.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
  src/main/resources/application.yaml
  src/test/java/com/prgrms/modi/common/jwt/JwtTest.java
  src/test/java/com/prgrms/modi/user/UserControllerTest.java
  src/test/java/com/prgrms/modi/user/domain/UserTest.java
  src/test/java/com/prgrms/modi/user/security/WithMockJwtAuthentication.java
  src/test/java/com/prgrms/modi/user/security/WithMockJwtAuthenticationSecurityContextFactory.java
  src/test/java/com/prgrms/modi/user/service/UserServiceTest.java
  src/test/resources/application.yaml
Labels: 👥 review, ✨ feature

#15 [MODI-79] 파티 생성 API 구현
  src/main/java/com/prgrms/modi/error/GlobalExceptionHandler.java
  src/main/java/com/prgrms/modi/error/exception/InvalidAuthenticationException.java
  src/main/java/com/prgrms/modi/party/PartyController.java
  src/main/java/com/prgrms/modi/party/PartyService.java
  src/main/java/com/prgrms/modi/party/controller/PartyController.java
  src/main/java/com/prgrms/modi/party/domain/Party.java
  src/main/java/com/prgrms/modi/party/domain/PartyRule.java
  src/main/java/com/prgrms/modi/party/dto/request/CreatePartyRequest.java
  src/main/java/com/prgrms/modi/party/dto/request/RuleRequest.java
  src/main/java/com/prgrms/modi/party/dto/response/PartyIdResponse.java
  src/main/java/com/prgrms/modi/party/dto/response/PartyListResponse.java
  src/main/java/com/prgrms/modi/party/dto/response/PartyResponse.java
  src/main/java/com/prgrms/modi/party/repository/PartyRepository.java
  src/main/java/com/prgrms/modi/party/repository/PartyRuleRepository.java
  src/main/java/com/prgrms/modi/party/repository/RuleRepository.java
  src/main/java/com/prgrms/modi/party/service/PartyRuleService.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/main/java/com/prgrms/modi/party/service/RuleService.java
  src/main/java/com/prgrms/modi/user/domain/Member.java
  src/main/java/com/prgrms/modi/user/repository/MemberRepository.java
  src/main/java/com/prgrms/modi/user/service/MemberService.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
  src/test/java/com/prgrms/modi/party/PartyControllerTest.java
  src/test/java/com/prgrms/modi/party/PartyServiceTest.java
Labels: 👥 review, ✨ feature

#18 [MODI-85] 유저 포인트 조회 API
  src/main/java/com/prgrms/modi/error/GlobalExceptionHandler.java
  src/main/java/com/prgrms/modi/user/controller/UserController.java
  src/main/java/com/prgrms/modi/user/domain/User.java
  src/main/java/com/prgrms/modi/user/dto/PointAmountDto.java
  src/main/java/com/prgrms/modi/user/dto/UserResponse.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
  src/test/java/com/prgrms/modi/user/controller/UserControllerTest.java
  src/test/java/com/prgrms/modi/user/domain/UserTest.java
  src/test/java/com/prgrms/modi/user/service/UserServiceTest.java
Labels: 👥 review, ✨ feature

#14 [MODI-75] FEAT : 캐루셀 조회 api
  src/main/java/com/prgrms/modi/ott/controller/OttRestController.java
  src/main/java/com/prgrms/modi/ott/dto/CarouselInfo.java
  src/main/java/com/prgrms/modi/ott/dto/CarouselListResponse.java
  src/main/java/com/prgrms/modi/ott/dto/CarouselResponse.java
  src/main/java/com/prgrms/modi/ott/repository/OttRepository.java
  src/main/java/com/prgrms/modi/ott/service/OttService.java
  src/main/resources/data.sql
  src/test/java/com/prgrms/modi/ott/controller/OttRestControllerTest.java
  src/test/java/com/prgrms/modi/ott/service/OttServiceTest.java
Labels: 👥 review, ✨ feature

#16 [MODI-120] 파티 목록 조회 API 응답에 파티 기간 추가
  src/main/java/com/prgrms/modi/party/domain/Party.java
  src/main/java/com/prgrms/modi/party/dto/response/PartyResponse.java
  src/main/resources/data.sql
  src/test/java/com/prgrms/modi/party/PartyServiceTest.java
Labels: 👥 review, ✨ feature

#17 [MODI-112] 전체 규칙 조회 API
  src/main/java/com/prgrms/modi/party/controller/PartyController.java
  src/main/java/com/prgrms/modi/party/domain/Rule.java
  src/main/java/com/prgrms/modi/party/dto/response/RuleListResponse.java
  src/main/java/com/prgrms/modi/party/dto/response/RuleResponse.java
  src/main/java/com/prgrms/modi/party/service/RuleService.java
  src/test/java/com/prgrms/modi/party/PartyControllerTest.java
  src/test/java/com/prgrms/modi/party/service/RuleServiceTest.java
Labels: 👥 review, ✨ feature

#20 [MODI-78] 유저 파티 참여 api 구현
  src/main/java/com/prgrms/modi/error/GlobalExceptionHandler.java
  src/main/java/com/prgrms/modi/error/exception/NotEnoughPartyCapacityException.java
  src/main/java/com/prgrms/modi/error/exception/NotEnoughPointException.java
  src/main/java/com/prgrms/modi/history/domain/CommissionHistory.java
  src/main/java/com/prgrms/modi/history/domain/PointHistory.java
  src/main/java/com/prgrms/modi/history/repository/CommissionHistoryRepository.java
  src/main/java/com/prgrms/modi/history/repository/PointHistoryRepository.java
  src/main/java/com/prgrms/modi/history/service/CommissionHistoryService.java
  src/main/java/com/prgrms/modi/history/service/PointHistoryService.java
  src/main/java/com/prgrms/modi/party/controller/PartyController.java
  src/main/java/com/prgrms/modi/party/domain/Party.java
  src/main/java/com/prgrms/modi/party/repository/PartyRepository.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/main/java/com/prgrms/modi/user/domain/Member.java
  src/main/java/com/prgrms/modi/user/domain/User.java
  src/main/java/com/prgrms/modi/user/service/MemberService.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
  src/main/resources/data.sql
  src/test/java/com/prgrms/modi/ott/controller/OttRestControllerTest.java
  src/test/java/com/prgrms/modi/ott/service/OttServiceTest.java
  src/test/java/com/prgrms/modi/party/PartyControllerTest.java
  src/test/java/com/prgrms/modi/party/PartyServiceTest.java
  src/test/java/com/prgrms/modi/user/controller/UserControllerTest.java
  src/test/java/com/prgrms/modi/utils/MockCreator.java
Labels: 👥 review, ✨ feature

#23 [MODI-80] OTT 공유 계정 api
  src/main/java/com/prgrms/modi/error/exception/InvalidAuthorizationException.java
  src/main/java/com/prgrms/modi/party/controller/PartyController.java
  src/main/java/com/prgrms/modi/party/dto/response/SharedAccountResponse.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/test/java/com/prgrms/modi/party/PartyControllerTest.java
Labels: 👥 review, ✨ feature

#21 [MODI-81] 유저 포인트 충전
  src/main/java/com/prgrms/modi/point/controller/PointController.java
  src/main/java/com/prgrms/modi/point/dto/PointAddRequest.java
  src/main/java/com/prgrms/modi/point/service/PointService.java
  src/main/java/com/prgrms/modi/user/domain/User.java
  src/main/java/com/prgrms/modi/user/dto/PointAmountDto.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
  src/test/java/com/prgrms/modi/ott/service/OttServiceTest.java
  src/test/java/com/prgrms/modi/point/controller/PointControllerTest.java
  src/test/java/com/prgrms/modi/point/service/PointServiceTest.java
Labels: 👥 review, ✨ feature

#25 [MODI-83] 유저가 참여한 파티 목록 조회 API 구현
  build.gradle
  src/main/java/com/prgrms/modi/common/configuration/QuerydslConfiguration.java
  src/main/java/com/prgrms/modi/party/controller/PartyController.java
  src/main/java/com/prgrms/modi/party/domain/Party.java
  src/main/java/com/prgrms/modi/party/dto/response/MemberResponse.java
  src/main/java/com/prgrms/modi/party/repository/PartyRepository.java
  src/main/java/com/prgrms/modi/party/repository/PartyRepositoryCustom.java
  src/main/java/com/prgrms/modi/party/repository/PartyRepositoryImpl.java
  src/main/java/com/prgrms/modi/user/controller/UserController.java
  src/main/java/com/prgrms/modi/user/domain/Member.java
  src/main/java/com/prgrms/modi/user/domain/User.java
  src/main/java/com/prgrms/modi/user/dto/UserPartyBriefResponse.java
  src/main/java/com/prgrms/modi/user/dto/UserPartyListResponse.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
  src/test/java/com/prgrms/modi/user/controller/UserControllerTest.java
  src/test/java/com/prgrms/modi/user/service/UserServiceTest.java
Labels: 👥 review, ✨ feature

#27 [MODI-82] 유저가 참여한 파티 상세 조회 API 구현
  build.gradle
  src/main/java/com/prgrms/modi/user/controller/UserController.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
  src/test/java/com/prgrms/modi/user/controller/UserControllerTest.java
  src/test/java/com/prgrms/modi/user/service/UserServiceTest.java
Labels: 👥 review, ✨ feature

#30 [MODI-149] REFACTOR : 로그인 시 USER ID 전달
  src/main/java/com/prgrms/modi/common/oauth2/OAuth2AuthenticationSuccessHandler.java
Labels: 👥 review, ♻ refactor

#33 [MODI-126] CHORE: 배포용 shell script 작성
  appspec.yml
  build.gradle
  scripts/deploy.sh
Labels: 💻 infra

#34 [MODI-168] 파티 컨트롤러 단위 테스트
  src/main/java/com/prgrms/modi/party/controller/PartyController.java
  src/main/java/com/prgrms/modi/party/dto/request/CreatePartyRequest.java
  src/main/java/com/prgrms/modi/party/dto/request/RuleRequest.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerTest.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerUnitTest.java
  src/test/java/com/prgrms/modi/party/controller/RuleControllerTest.java
  src/test/java/com/prgrms/modi/party/service/PartyServiceTest.java
  src/test/java/com/prgrms/modi/party/service/RuleServiceTest.java
  src/test/java/com/prgrms/modi/utils/MockCreator.java
Labels: ♻ refactor

#37 [MODI-169] REFACTOR : 유저 DTO 응답 필드 추가
  src/main/java/com/prgrms/modi/party/dto/response/MemberResponse.java
  src/main/java/com/prgrms/modi/party/repository/PartyRepositoryImpl.java
  src/main/java/com/prgrms/modi/user/dto/PointAmountDto.java
  src/main/java/com/prgrms/modi/user/dto/UserPartyBriefResponse.java
  src/main/java/com/prgrms/modi/user/dto/UserPartyListResponse.java
Labels: 👥 review, ♻ refactor

#39 [MODI-173] CHORE: RDS 환경설정 추가
  build.gradle
  scripts/deploy.sh
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
  src/main/resources/db/migration/V2021.12.09.1745__init.sql
  src/test/resources/application.yaml
Labels: 💻 infra

#38 [MODI-178] REFACTOR: 전체 OTT 서비스 조회 API 리팩토링
  src/main/java/com/prgrms/modi/ott/controller/OttController.java
  src/main/java/com/prgrms/modi/ott/service/OttService.java
  src/main/java/com/prgrms/modi/party/controller/PartyController.java
  src/main/java/com/prgrms/modi/party/controller/RuleController.java
  src/main/java/com/prgrms/modi/party/domain/Party.java
  src/main/java/com/prgrms/modi/party/repository/PartyRepository.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/main/java/com/prgrms/modi/party/service/RuleService.java
  src/main/java/com/prgrms/modi/point/controller/PointController.java
  src/main/java/com/prgrms/modi/point/service/PointService.java
  src/main/java/com/prgrms/modi/user/controller/UserController.java
  src/main/java/com/prgrms/modi/user/dto/PointAmountResponse.java
  src/main/java/com/prgrms/modi/user/service/MemberService.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
  src/test/java/com/prgrms/modi/ott/controller/OttControllerTest.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerUnitTest.java
  src/test/java/com/prgrms/modi/party/service/PartyServiceTest.java
  src/test/java/com/prgrms/modi/point/service/PointServiceTest.java
  src/test/java/com/prgrms/modi/user/service/UserServiceTest.java
  src/test/java/com/prgrms/modi/utils/MockCreator.java
Labels: 👥 review, ♻ refactor

#41 [MODI-186] Ott Response 에 Swagger 추가, OttNameResponse 추가
  src/main/java/com/prgrms/modi/ott/domain/OTT.java
  src/main/java/com/prgrms/modi/ott/dto/CarouselListResponse.java
  src/main/java/com/prgrms/modi/ott/dto/CarouselResponse.java
  src/main/java/com/prgrms/modi/ott/dto/OttListResponse.java
  src/main/java/com/prgrms/modi/ott/dto/OttNameResponse.java
  src/main/java/com/prgrms/modi/ott/dto/OttResponse.java
  src/main/java/com/prgrms/modi/party/domain/Party.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/main/resources/db/migration/V2021.12.13.1814__addOttEnglishName.sql
  src/main/resources/db/seed/R__seed.sql
  src/test/java/com/prgrms/modi/ott/controller/OttControllerTest.java
  src/test/java/com/prgrms/modi/ott/service/OttServiceTest.java
  src/test/java/com/prgrms/modi/utils/MockCreator.java
  src/test/resources/db/seed/R__seed.sql
Labels: 👥 review, ♻ refactor, 📝 docs

#47 [MODI-105] 사용자 생년월일 인증 로직 수정
  src/main/java/com/prgrms/modi/common/oauth2/info/KakaoOAuth2UserInfo.java
  src/main/java/com/prgrms/modi/common/oauth2/info/NaverOAuth2UserInfo.java
  src/main/java/com/prgrms/modi/common/oauth2/info/OAuth2UserInfo.java
  src/main/java/com/prgrms/modi/error/GlobalExceptionHandler.java
  src/main/java/com/prgrms/modi/error/exception/NotEnoughAgeException.java
  src/main/java/com/prgrms/modi/error/exception/NotEnoughUserInformationException.java
  src/main/java/com/prgrms/modi/party/dto/response/RuleResponse.java
  src/main/java/com/prgrms/modi/user/domain/User.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
  src/main/resources/db/migration/V2021.12.14.1545__dropUserBod.sql
  src/main/resources/db/seed/R__seed.sql
  src/test/java/com/prgrms/modi/user/domain/UserTest.java
  src/test/resources/db/seed/R__seed.sql
Labels: 👥 review, ♻ refactor

#46 [MODI-171] ERROR 로그 슬랙 알림 설정
  build.gradle
  src/main/resources/application-prod.yaml
  src/main/resources/logback.xml
Labels: 💻 infra

#49 [MODI-198] FEAT : 백앤드 서버 상태 체크용 api 만들기
  src/main/java/com/prgrms/modi/common/controller/CommonController.java
Labels: 👥 review

#48 [MODI-192] FEAT : 파티 환급 로직 구현
  src/main/java/com/prgrms/modi/common/scheduler/ReimbursementScheduler.java
  src/main/java/com/prgrms/modi/common/scheduler/SchedulerConfiguration.java
  src/main/java/com/prgrms/modi/party/domain/Party.java
  src/main/java/com/prgrms/modi/party/dto/request/CreatePartyRequest.java
  src/main/java/com/prgrms/modi/party/repository/PartyRepository.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/main/java/com/prgrms/modi/user/domain/User.java
  src/test/java/com/prgrms/modi/party/service/PartyIntegrationTest.java
  src/test/resources/db/seed/R__seed.sql
Labels: 👥 review, ✨ feature

#50 [MODI-194] FEAT : 파티 상태 변경 로직 구현
  src/main/java/com/prgrms/modi/common/scheduler/ReimbursementScheduler.java
  src/main/java/com/prgrms/modi/party/domain/Party.java
  src/main/java/com/prgrms/modi/party/repository/PartyRepository.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/test/java/com/prgrms/modi/party/service/PartyIntegrationTest.java
  src/test/resources/db/seed/R__seed.sql
Labels: 👥 review, ✨ feature

#51 Version 1.0.2
  build.gradle
  src/main/java/com/prgrms/modi/common/controller/CommonController.java
  src/main/java/com/prgrms/modi/common/oauth2/info/KakaoOAuth2UserInfo.java
  src/main/java/com/prgrms/modi/common/oauth2/info/NaverOAuth2UserInfo.java
  src/main/java/com/prgrms/modi/common/oauth2/info/OAuth2UserInfo.java
  src/main/java/com/prgrms/modi/common/scheduler/ReimbursementScheduler.java
  src/main/java/com/prgrms/modi/common/scheduler/SchedulerConfiguration.java
  src/main/java/com/prgrms/modi/error/GlobalExceptionHandler.java
  src/main/java/com/prgrms/modi/error/exception/NotEnoughAgeException.java
  src/main/java/com/prgrms/modi/error/exception/NotEnoughUserInformationException.java
  src/main/java/com/prgrms/modi/party/domain/Party.java
  src/main/java/com/prgrms/modi/party/dto/request/CreatePartyRequest.java
  src/main/java/com/prgrms/modi/party/dto/response/RuleResponse.java
  src/main/java/com/prgrms/modi/party/repository/PartyRepository.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/main/java/com/prgrms/modi/user/domain/User.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
  src/main/resources/db/migration/V2021.12.14.1545__dropUserBod.sql
  src/main/resources/db/seed/R__seed.sql
  src/main/resources/logback.xml
  src/test/java/com/prgrms/modi/party/service/PartyIntegrationTest.java
  src/test/java/com/prgrms/modi/user/domain/UserTest.java
  src/test/resources/db/seed/R__seed.sql
Labels: 🚀 deploy

#52 [MODI-207] FEAT : ott별 모집중인 파티 목록에서도 totalsize 를 보이도록 변경
  src/main/java/com/prgrms/modi/party/dto/response/PartyListResponse.java
  src/main/java/com/prgrms/modi/party/repository/PartyRepository.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/main/java/com/prgrms/modi/user/dto/UserPartyListResponse.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerTest.java
Labels: 👥 review, ✨ feature

#53 [MODI-208] REFACTOR : 캐루셀의 waitingForMatch 가 팀단위가 아니라 명 단위로 변경
  src/main/java/com/prgrms/modi/ott/dto/CarouselResponse.java
  src/main/java/com/prgrms/modi/ott/repository/OttRepository.java
  src/main/java/com/prgrms/modi/party/domain/Party.java
  src/main/resources/application-prod.yaml
  src/test/java/com/prgrms/modi/ott/controller/OttControllerTest.java
  src/test/resources/application.yaml
Labels: 👥 review, ♻ refactor

#54 [MODI-221] FEAT: 닉네임 랜덤생성 API 추가
  src/main/java/com/prgrms/modi/user/controller/UserController.java
  src/main/java/com/prgrms/modi/user/dto/UsernameListResponse.java
  src/main/java/com/prgrms/modi/user/dto/UsernameResponse.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
  src/test/java/com/prgrms/modi/user/controller/UserControllerTest.java
Labels: 👥 review, ✨ feature

#55 [MODI-222] 사용자 닉네임 변경 API 추가
  src/main/java/com/prgrms/modi/error/exception/InvalidUsernameException.java
  src/main/java/com/prgrms/modi/user/controller/UserController.java
  src/main/java/com/prgrms/modi/user/domain/User.java
  src/main/java/com/prgrms/modi/user/dto/UsernameRequest.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
  src/main/java/com/prgrms/modi/utils/UsernameGenerator.java
  src/test/java/com/prgrms/modi/user/controller/UserControllerTest.java
Labels: 👥 review, ✨ feature

#58 [MODI-231] PATCH 메소드 CORS 문제
  src/main/java/com/prgrms/modi/common/configuration/MvcConfiguration.java
Labels: 🐛 bug, ♻ refactor

#56 Version 1.0.3
  src/main/java/com/prgrms/modi/common/configuration/MvcConfiguration.java
  src/main/java/com/prgrms/modi/error/exception/InvalidUsernameException.java
  src/main/java/com/prgrms/modi/ott/dto/CarouselResponse.java
  src/main/java/com/prgrms/modi/ott/repository/OttRepository.java
  src/main/java/com/prgrms/modi/party/domain/Party.java
  src/main/java/com/prgrms/modi/party/dto/response/PartyListResponse.java
  src/main/java/com/prgrms/modi/party/repository/PartyRepository.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/main/java/com/prgrms/modi/user/controller/UserController.java
  src/main/java/com/prgrms/modi/user/domain/User.java
  src/main/java/com/prgrms/modi/user/dto/UserPartyListResponse.java
  src/main/java/com/prgrms/modi/user/dto/UsernameListResponse.java
  src/main/java/com/prgrms/modi/user/dto/UsernameRequest.java
  src/main/java/com/prgrms/modi/user/dto/UsernameResponse.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
  src/main/java/com/prgrms/modi/utils/UsernameGenerator.java
  src/main/resources/application-prod.yaml
  src/test/java/com/prgrms/modi/ott/controller/OttControllerTest.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerTest.java
  src/test/java/com/prgrms/modi/user/controller/UserControllerTest.java
  src/test/resources/application.yaml
Labels: 🚀 deploy

#57 [MODI-225] 파티 공유 계정 수정 API 구현
  src/main/java/com/prgrms/modi/party/controller/PartyController.java
  src/main/java/com/prgrms/modi/party/domain/Party.java
  src/main/java/com/prgrms/modi/party/dto/request/UpdateSharedAccountRequest.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerTest.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerUnitTest.java
Labels: 👥 review, ✨ feature

#61 [MODI-226] 파티 삭제 API 구현
  src/main/java/com/prgrms/modi/common/domain/DeletableEntity.java
  src/main/java/com/prgrms/modi/party/controller/PartyController.java
  src/main/java/com/prgrms/modi/party/domain/Party.java
  src/main/java/com/prgrms/modi/party/dto/request/CreatePartyRequest.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/test/java/com/prgrms/modi/ott/controller/OttControllerTest.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerTest.java
  src/test/java/com/prgrms/modi/party/service/PartyIntegrationTest.java
  src/test/resources/db/seed/R__seed.sql
Labels: 👥 review, ✨ feature

#63 [MODI-238] REFACTOR : 캐루셀 조회 쿼리 조건 추가
  src/main/java/com/prgrms/modi/ott/repository/OttRepository.java
Labels: 👥 review, 🐛 bug

#65 [MODI-244] REFACTOR: 나이 관련 인증 실패 시 필수정보 부족 예외처리
  src/main/java/com/prgrms/modi/common/oauth2/info/KakaoOAuth2UserInfo.java
  src/main/java/com/prgrms/modi/common/oauth2/info/NaverOAuth2UserInfo.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
Labels: 🐛 bug, ♻ refactor

#67 [MODI-227] REFACTOR: 유저 참여 파티 목록 관련 필드 수정
  build.gradle
  src/main/java/com/prgrms/modi/party/repository/PartyRepositoryImpl.java
  src/main/java/com/prgrms/modi/user/controller/UserController.java
  src/main/java/com/prgrms/modi/user/dto/UserPartyBriefResponse.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerTest.java
  src/test/java/com/prgrms/modi/user/controller/UserControllerTest.java
  src/test/resources/db/seed/R__seed.sql
Labels: 🐛 bug, ♻ refactor

#66 [MODI-195] FEAT : 삭제 대상 한 달 후에 제거 로직 구현
  src/main/java/com/prgrms/modi/common/scheduler/ReimbursementScheduler.java
  src/main/java/com/prgrms/modi/party/repository/PartyRepository.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/main/resources/db/migration/V2021.12.20.1350__changeMemberConstraint.sql
  src/test/java/com/prgrms/modi/party/service/PartyIntegrationTest.java
Labels: 👥 review, ✨ feature

#68 [MODI-268] DOCS: README 전체 수정
  README.md
Labels: 👥 review, 📝 docs

#69 [MODI-244] 나이인증 관련 hotfix 수정된 부분 develop 브랜치에 반영
  src/main/java/com/prgrms/modi/common/oauth2/info/KakaoOAuth2UserInfo.java
  src/main/java/com/prgrms/modi/common/oauth2/info/NaverOAuth2UserInfo.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
Labels: ♻ refactor

#70 [MODI-227] 유저 참여 파티 목록 필드 hotfix 수정된 부분 develop 브랜치에 반영
  build.gradle
  src/main/java/com/prgrms/modi/party/repository/PartyRepositoryImpl.java
  src/main/java/com/prgrms/modi/user/controller/UserController.java
  src/main/java/com/prgrms/modi/user/dto/UserPartyBriefResponse.java
  src/main/java/com/prgrms/modi/user/service/UserService.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerTest.java
  src/test/java/com/prgrms/modi/user/controller/UserControllerTest.java
  src/test/resources/db/seed/R__seed.sql
Labels: ♻ refactor

#71 Version 1.0.6
  README.md
  build.gradle
  src/main/java/com/prgrms/modi/common/scheduler/ReimbursementScheduler.java
  src/main/java/com/prgrms/modi/party/repository/PartyRepository.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/main/resources/db/migration/V2021.12.20.1350__changeMemberConstraint.sql
  src/main/resources/db/seed/R__seed.sql
  src/test/java/com/prgrms/modi/party/service/PartyIntegrationTest.java
Labels: 🚀 deploy

#73 [MODI-276] REFACTOR : 유저 파티 참여시 수수료 포함해서 결제
  src/main/java/com/prgrms/modi/history/service/CommissionHistoryService.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerTest.java
Labels: 👥 review, 🐛 bug, ♻ refactor

#74 [MODI-236] 파티 생성 최소 날짜 수정 후 관련 테스트 수정
  src/main/java/com/prgrms/modi/party/domain/PartyRulePK.java
  src/main/java/com/prgrms/modi/party/dto/request/CreatePartyRequest.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerTest.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerUnitTest.java
  src/test/java/com/prgrms/modi/party/service/PartyIntegrationTest.java
Labels: 👥 review, 🐛 bug, ♻ refactor

#72 [MODI-274] REFACTOR : 파티가입시 트랜젝션 관리
  src/main/java/com/prgrms/modi/error/GlobalExceptionHandler.java
  src/main/java/com/prgrms/modi/error/exception/RequestAgainException.java
  src/main/java/com/prgrms/modi/party/controller/PartyController.java
  src/main/java/com/prgrms/modi/party/domain/Party.java
  src/main/resources/db/migration/V2021.12.20.2207__addVersionInParty.sql
  src/main/resources/db/migration/V2021.12.21.1053__addUniqueInMember.sql
  src/test/java/com/prgrms/modi/party/controller/PartyControllerTest.java
  src/test/resources/db/seed/R__seed.sql
Labels: 👥 review, ♻ refactor
