Repository prgrms-web-devcourse/Team_MODI_MODI_BE, pull requests merged in 2022-01, with the labels that each got.

#78 [MODI-170] 알림 기능 - SSE 연결, 기본 알림 구현
  src/main/java/com/prgrms/modi/notification/controller/NotificationController.java
  src/main/java/com/prgrms/modi/notification/domain/Notification.java
  src/main/java/com/prgrms/modi/notification/dto/NotificationResponse.java
  src/main/java/com/prgrms/modi/notification/repository/EmitterRepository.java
  src/main/java/com/prgrms/modi/notification/repository/NotificationRepository.java
  src/main/java/com/prgrms/modi/notification/service/NotificationService.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/main/resources/application-prod.yaml
  src/main/resources/db/migration/V2022.1.11.1243__createNotifications.sql
  src/test/java/com/prgrms/modi/notification/controller/NotificationControllerTest.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerTest.java
  src/test/java/com/prgrms/modi/party/service/PartyServiceTest.java
  src/test/resources/db/seed/R__seed.sql
Labels: ✨ feature

#80 [MODI-292] 알림 기능 - 전체 알림 조회 API 구현
  src/main/java/com/prgrms/modi/notification/controller/NotificationController.java
  src/main/java/com/prgrms/modi/notification/domain/Notification.java
  src/main/java/com/prgrms/modi/notification/dto/NotificationResponse.java
  src/main/java/com/prgrms/modi/notification/dto/NotificationsResponse.java
  src/main/java/com/prgrms/modi/notification/repository/NotificationRepository.java
  src/main/java/com/prgrms/modi/notification/service/NotificationService.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/main/java/com/prgrms/modi/user/domain/Member.java
  src/main/java/com/prgrms/modi/user/repository/MemberRepository.java
  src/main/resources/db/migration/V2022.1.15.2325__chageNotification.sql
  src/test/java/com/prgrms/modi/notification/controller/NotificationControllerTest.java
  src/test/java/com/prgrms/modi/ott/controller/OttControllerTest.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerTest.java
  src/test/java/com/prgrms/modi/party/service/PartyIntegrationTest.java
  src/test/resources/db/seed/R__seed.sql
Labels: ✨ feature

#81 [MODI-293] 알림 기능 - 알림 삭제(읽음) API 구현
  src/main/java/com/prgrms/modi/notification/controller/NotificationController.java
  src/main/java/com/prgrms/modi/notification/service/NotificationService.java
  src/main/java/com/prgrms/modi/user/domain/Member.java
  src/main/java/com/prgrms/modi/user/repository/MemberRepository.java
  src/test/java/com/prgrms/modi/notification/controller/NotificationControllerTest.java
  src/test/java/com/prgrms/modi/notification/domain/NotificationTest.java
  src/test/java/com/prgrms/modi/notification/service/NotificationServiceTest.java
  src/test/java/com/prgrms/modi/ott/controller/OttControllerTest.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerTest.java
  src/test/java/com/prgrms/modi/party/service/PartyIntegrationTest.java
  src/test/java/com/prgrms/modi/user/domain/UserTest.java
  src/test/java/com/prgrms/modi/utils/MockCreator.java
  src/test/resources/db/seed/R__seed.sql
Labels: ✨ feature

#83 main 브랜치 암호화 hotfix한 부분 develop 브랜치에도 반영
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/test/java/com/prgrms/modi/party/controller/PartyControllerTest.java
Labels: ♻ refactor

#85 [MODI-301] REFACTOR : 파티 삭제 시에 맴버 삭제 되는 부분 구현
  src/main/java/com/prgrms/modi/common/scheduler/ReimbursementScheduler.java
  src/main/java/com/prgrms/modi/party/repository/PartyRepository.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/main/java/com/prgrms/modi/user/repository/MemberRepository.java
  src/test/java/com/prgrms/modi/party/service/PartyIntegrationTest.java
Labels: 👥 review, 🐛 bug

#86 [MODI-291] 알림 기능 - 스케쥴러 관련 알림 구현
  src/main/java/com/prgrms/modi/common/scheduler/ReimbursementScheduler.java
  src/main/java/com/prgrms/modi/party/service/PartyService.java
  src/test/java/com/prgrms/modi/party/service/PartyIntegrationTest.java
Labels: ✨ feature
